### ISSUE TITLE
User API 응답 에러 해결

### ISSUE THREAD

**Issue by mtseo01** [mtseo01/vue-toy#2]
[에러]
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:372:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (/Users/seomintaek/Documents/projects/vue/login/server/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/Users/seomintaek/Documents/projects/vue/login/server/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/Users/seomintaek/Documents/projects/vue/login/server/node_modules/express/lib/response.js:278:15)
    at /Users/seomintaek/Documents/projects/vue/login/server/api/controllers/user.js:44:40
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

[원인]
응답을 두 번 이상하게 될 경우 에러 발생

[해결]
에러로 보이는 코드 코멘트 처리.
확인 후 코멘트 삭제

**Comment by mtseo01** [comment]
해결
